[package]
name = "wump"
version = "0.1.0"

[dependencies]
rppal = { version = "*", features = ["hal"] }
ssd1322 = "*"
chrono     = "0.4"
mpd        = "*"
bitflags   = "*"
rouille    = "*"
tinytemplate = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"

[patch.crates-io]
ssd1322 = { path = 'ssd1322' }