[package]
name = "wump"
version = "0.1.0"


[dependencies]
sysfs_gpio = "0.5"
retry      = "0.5.1"
i2cdev     = "0.4.2"
chrono     = "0.4"
mpd        = "*"
bitflags   = "*"
rouille    = "*"
tinytemplate = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"