[package]
name = "wump"
version = "0.5.0"

[dependencies]
chrono     = "*"
mpd        = "*"
bitflags   = "*"
rppal      = "*"
spidev     = "*"
rusttype   = "*"
rouille    = "*"
tinytemplate = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
