[package]
name = "wump"
version = "0.1.0"

[dependencies]
chrono     = "*"
mpd        = "*"
bitflags   = "*"
rouille    = "*"
tinytemplate = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
rppal = { version = "*", features = ["hal"] }
spidev = "*"
rusttype   = "*"

